DROP SCHEMA IF EXISTS schoolSH CASCADE ;
DROP ROLE IF EXISTS userDB;

CREATE ROLE userDB WITH LOGIN ENCRYPTED PASSWORD '123';
CREATE SCHEMA schoolSH ;

CREATE TABLE schoolSH.students(
STUDENT_ID INT PRIMARY KEY,
GROUP_ID INT,
FIRST_NAME TEXT,
LAST_NAME TEXT);

CREATE TABLE schoolSH.courses(
COURSES_ID INT PRIMARY KEY,
COURSES_NAME TEXT,
COURSES_DESCRIPTION TEXT);

CREATE TABLE schoolSH.groups(
GROUP_ID INT PRIMARY KEY,
GROUP_NAME TEXT);



