DROP SCHEMA IF EXISTS school CASCADE ;
DROP ROLE IF EXISTS userDB;
CREATE ROLE userDB WITH LOGIN ENCRYPTED PASSWORD '123';
CREATE SCHEMA school ;
CREATE TABLE school.students(
STUDENT_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
GROUP_ID INT,
FIRST_NAME TEXT,
LAST_NAME TEXT);
CREATE TABLE school.courses(
COURSE_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
COURSE_NAME TEXT,
COURSE_DESCRIPTION TEXT);
CREATE TABLE school.groups(
GROUP_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
GROUP_NAME TEXT);

CREATE TABLE school.students_courses(
STUDENT_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
COURSE_ID INT);

--CREATE TABLE school.students_courses(
--STUDENT_ID INT,
--COURSE_ID INT,
--PRIMARY KEY (STUDENT_ID, COURSE_ID),
--CONSTRAINT student FOREIGN KEY(STUDENT_ID) REFERENCES school.students(STUDENT_ID),
--CONSTRAINT course FOREIGN KEY(COURSE_ID) REFERENCES school.courses(COURSE_ID)
--);
