DROP SCHEMA IF EXISTS school CASCADE ;
DROP ROLE IF EXISTS userDB;

CREATE ROLE userDB WITH LOGIN ENCRYPTED PASSWORD '123';
CREATE SCHEMA school ;

CREATE TABLE school.students(
STUDENT_ID INT PRIMARY KEY,
GROUP_ID INT,
FIRST_NAME TEXT,
LAST_NAME TEXT);

CREATE TABLE school.courses(
COURSES_ID INT PRIMARY KEY,
COURSES_NAME TEXT,
COURSES_DESCRIPTION TEXT);

CREATE TABLE school.groups(
GROUP_ID INT PRIMARY KEY,
GROUP_NAME TEXT);



